# Generated by Django 3.2.7 on 2021-10-04 16:21

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211004_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='cpc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='cpm',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
