# Generated by Django 3.2.7 on 2021-10-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211004_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='cpc',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistics',
            name='cpm',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=17),
            preserve_default=False,
        ),
    ]
