version: '3.9'

services:
  web:
    build: ./backend
    container_name: microservice_REST
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000
    volumes:
    - ./backend/:/usr/src/backend
    environment:
    - REDIS_HOST=redis
    env_file:
    - ./.env.dev
    links:
    - redis

  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_DB=db
    - POSTGRES_USER=db_user
    - POSTGRES_PASSWORD=password

  
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: